### ISSUE TITLE
Expired keys leave the system in an inconsistent state

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/mustached-octo-ironman#18]
@wasade and I realized that keys that expire can leave the system in an inconsistent state. You could get to the point where a key's parent/children expires and this causes havoc with the system.

This problem "artificially" seems to be resolved by clearing the redis database or purging the orphan keys. The bug will "eventually" show up every two weeks, as that's the timeout being set [here](https://github.com/biocore/mustached-octo-ironman/blob/master/moi/__init__.py).

**Comment by ElDeveloper** [comment]
As a side note, an error with code 502 will show up in the JavaScript console.

**Comment by wasade** [comment]
Resolved in #26
